//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesStore9_13.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusCard
    {
        public int IDBonusCard { get; set; }
        public decimal NumberOfBonuses { get; set; }
    }
}
