//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesStore9_13.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int IDPassport { get; set; }
        public int Series { get; set; }
        public int Number { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string IssueBy { get; set; }
    }
}
